#!/bin/bash

# This shell script was written in order to help you to create and maintain your
# local mirrors of MOS and/or Ubuntu. You could use this script as a cron job.
# Dependencies: rsync, wget, gpg, docker + dpkg-dev (only for partial Ubuntu mirror)

usage(){
cat <<EOF
Usage: create_mirror [-h|--help] | [mos|ubuntu]
Create and update local mirrors of MOS and/or Ubuntu.

   -h| --help      This help screen.

Actions could be one of:

   mos             Create/Update MOS local mirror only
   ubuntu          Create/Update Ubuntu local mirror only

If no parameters specified, script will Create/Update both MOS and Ubuntu mirrors.

EOF
}

die() { echo "$@" 1>&2 ; exit 1; }

if [[ ( "$1" == "--help" ) ||  ( "$1" == "-h" ) ]]; then 
    usage
    exit 0
fi 

BINROOT=$(dirname `readlink -f "$0"`)

. $BINROOT/config/common.cfg

mkdir -p ${MIRROR_ROOT} || die "Cannot create ${MIRROR_ROOT}, exiting."
mkdir -p ${LOG_ROOT} || die "Cannot create ${LOG_ROOT}, exiting."

[ "$1" != "ubuntu" ] && $BINROOT/deb-mirror $BINROOT/config/mos-ubuntu-updatesonly.cfg
[ "$1" != "mos" ] && $BINROOT/deb-mirror $BINROOT/config/ubuntu.cfg

[ "$1" != "ubuntu" ] && . $BINROOT/config/mos-ubuntu-updatesonly.cfg && echo " * INFO: MOS mirror was created at: $LOCAL_DIR"
if [[ "$1" != "mos" ]]; then
    . $BINROOT/config/ubuntu.cfg
    if [[ $PARTIAL_UPSTREAM = "1" ]]; then
	 echo " * INFO: Ubuntu partial mirror was created at: $PARTIAL_UPSTREAM_PATH"
    else
	echo " * INFO: Ubuntu mirror was created at: $LOCAL_DIR"
    fi
fi
